### ISSUE TITLE
Question about metrics

### ISSUE THREAD

**Issue by jhjacobs81** [Lusitaniae/apache_exporter#141]
I am very new to both Grafana and Apache exporter, and i was curious.
What is the difference between this one:
# TYPE apache_accesses_total counter

and this one:
# TYPE apache_duration_ms_total gauge

I am looking for a way to show the response times of how long it takes when i request a page, and when apache says its finished. For one client they have a request that it takes no longer then so many ms between request and completion :)

**Comment by jhjacobs81** [comment]
i am looking for a way to show how long it takes a page to load.. not sure which one to use!

**Comment by blkperl** [comment]
Hey @jhjacobs81 ,

- apache_accesses_total is good for calculating requests per second. 
- apache_duration_ms_total would tell you how long a request took. Since a page is often multiple requests to different resources it wouldn't tell you how long a page takes to load. A different tool would be more suitable to measure page load time.

**Comment by MarcinPrzadlo** [comment]
Actually for different tool you would need to analizę apache text
accesslogs. (Httpd would need to be set to log %D )

Check goaccess

Or send logs to Loki and graph the request duration.



pt., 17 lut 2023, 21:19 użytkownik William Van Hevelingen <
***@***.***> napisał:

**Comment by blkperl** [comment]
Let us know if you have any more questions
