### ISSUE TITLE
Can one instance of apache_exporter monitor two or more apache instances?

### ISSUE THREAD

**Issue by ping2nomula** [Lusitaniae/apache_exporter#37]
We have two or more apache instances on the same host and wants to monitor it using apache_exporter. Do i need to have more instances of apache_exporter running or one is enough?

**Comment by Lusitaniae** [comment]
Yes, Prometheus philosophy is to have one exporter process for each thing being monitored.

**Comment by mmranger** [comment]
> You need multiple instances.
> Prometheus philosophy is to have one exporter process for each thing being monitored.

Would multiple vhosts/sites be considered multiple 'instances'?  Also doesn't your phpfpm_exporter handle multiple instances via --phpfpm.socket-paths?

Example: Server running 3 vhosts, and two versions of php.  With this setup I use one phpfpm_exporter with the two php versions.  But I need to setup 3 apache_exporters(0-2) to accommodate each vhost/site.

Of course I don't know golang/apache/php well anyway, so if this is an annoying (my example setup is flawed for instance) question feel free to ignore.

Thanks.

**Comment by Lusitaniae** [comment]
Apache can serve multiple vhosts from the same process. Therefore there
will be one exporter per Apache instance.


Phpfpm exporter does not follow the convention, because you can create
multiple fpm pools and need to monitor each one individually, and the
exporter will monitor all from one instance (against convention)

If you’re running different Apache instances, because you may want to
segregate stats per vhost, then you’ll need different exporters for each
instance


Hope it’s clear

**Comment by leonk** [comment]
Don’t suppose anyone has an example of how to set this up with kubernetes?

I’m able to create two separate services in k8ns, but not sure how I could get each individual pod running the apache exporter to connect directly to a pod running Apache.

**Comment by Lusitaniae** [comment]
Typically you use a "sidecar container pattern" approach

So each Apache container will have an apache exporter sidecar container

Maybe this article can guide you

https://medium.com/bb-tutorials-and-thoughts/kubernetes-learn-sidecar-container-pattern-6d8c21f873d
