### ISSUE TITLE
Apache RAM/fds usage metrics

### ISSUE THREAD

**Issue by vkuznet** [Lusitaniae/apache_exporter#62]
Would it be possible to add apache RAM and fds usage? So far I see process RAM/fds metrics, but I think process means metrics of the exporters and not apache server.

**Comment by Lusitaniae** [comment]
Indeed, they're exporter process metrics.

We only export CPU metrics since they're provided by the status page itself, 
but even that seems to go against the best practices.

I don't think we'll add RAM and fds metrics for that reason. 

Please see below:

https://prometheus.io/docs/instrumenting/writing_exporters/#machine-and-process-metrics

> Machine and process metrics
> 
> Many systems, for example Elasticsearch, expose machine metrics such as CPU, memory and filesystem information. As the node exporter provides these in the Prometheus ecosystem, such metrics should be dropped.
